-- ============================================================
-- BABUU PLATFORM — SCHEMA V2 EXTENSION
-- Run AFTER schema.sql. Adds: task boards, competitor spy,
-- knowledge base, AI news digests, and scheduling support.
-- ============================================================

-- ============================================================
-- TASKS
-- Per-brand task board. Ownership, deadlines, status tracking.
-- Auto-updated by Babuu when it completes work.
-- ============================================================
CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'review', 'done', 'blocked')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('urgent', 'high', 'medium', 'low')),
  owner TEXT,                        -- person or 'babuu' when automated
  due_date DATE,
  category TEXT,                     -- 'content', 'ads', 'seo', 'design', 'video', 'email', 'strategy', 'admin'
  linked_entity_type TEXT,           -- 'content_calendar', 'ad_campaigns', 'content_lab_tests', 'video_assets'
  linked_entity_id UUID,             -- when done, the linked entity auto-closes this task
  auto_completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  created_by TEXT DEFAULT 'user',    -- 'user' or 'babuu'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tasks_brand_status ON tasks(brand_id, status);
CREATE INDEX idx_tasks_due ON tasks(due_date) WHERE status != 'done';

-- ============================================================
-- COMPETITOR SWIPES
-- Up-to-date swipe file of competitor organic posts and paid ads.
-- ============================================================
CREATE TABLE competitor_swipes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  competitor_name TEXT NOT NULL,
  competitor_handle TEXT,
  platform TEXT NOT NULL,            -- 'facebook', 'instagram', 'tiktok', 'youtube', 'x', 'threads', 'google_ads', 'meta_ads'
  swipe_type TEXT NOT NULL CHECK (swipe_type IN ('organic_post', 'paid_ad', 'landing_page', 'email', 'funnel')),
  content_url TEXT,                  -- link to the original
  media_url TEXT,                    -- screenshot/asset stored in Cloudinary
  headline TEXT,
  body_copy TEXT,
  cta TEXT,
  format TEXT,                       -- 'reel', 'carousel', 'static', 'video', 'story'
  first_seen DATE NOT NULL DEFAULT CURRENT_DATE,
  last_seen DATE NOT NULL DEFAULT CURRENT_DATE,
  still_running BOOLEAN DEFAULT TRUE,   -- for ads: long-running = likely profitable
  engagement_snapshot JSONB,            -- likes, comments, shares at capture time
  babuu_analysis TEXT,                  -- why this works, what to learn from it
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_swipes_brand ON competitor_swipes(brand_id);
CREATE INDEX idx_swipes_competitor ON competitor_swipes(brand_id, competitor_name);

-- ============================================================
-- KNOWLEDGE DOCUMENTS
-- The "dump files" master memory. Workshop notes, program PDFs,
-- courses — uploaded, summarized by Babuu, chunked into
-- strategy_embeddings for semantic recall.
-- ============================================================
CREATE TABLE knowledge_documents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,  -- NULL = studio-wide knowledge
  title TEXT NOT NULL,
  source_type TEXT NOT NULL CHECK (source_type IN ('workshop', 'course', 'program', 'book', 'article', 'meeting_notes', 'other')),
  original_filename TEXT,
  file_url TEXT,                     -- storage location
  raw_text TEXT,                     -- extracted text
  babuu_summary TEXT,                -- auto-generated summary
  key_takeaways JSONB DEFAULT '[]',  -- auto-extracted actionable points
  embedded BOOLEAN DEFAULT FALSE,    -- whether chunks are in strategy_embeddings
  uploaded_by TEXT DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_knowledge_brand ON knowledge_documents(brand_id);

-- ============================================================
-- AI NEWS DIGESTS
-- Daily digest of AI news for marketing, social, and sales outreach.
-- Generated by the ai-news cron, displayed in the dashboard.
-- ============================================================
CREATE TABLE ai_news_digests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  digest_date DATE NOT NULL UNIQUE,
  items JSONB NOT NULL DEFAULT '[]',    -- [{title, summary, why_it_matters, source_url, category}]
  babuu_take TEXT,                       -- one strategic takeaway for the studio
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- EMAIL / SMS SEQUENCES
-- Promotion and high-value content sequences per brand.
-- ============================================================
CREATE TABLE message_sequences (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('email', 'sms')),
  sequence_type TEXT NOT NULL CHECK (sequence_type IN ('promotion', 'nurture', 'newsletter', 'onboarding', 'winback')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'active', 'paused', 'archived')),
  messages JSONB NOT NULL DEFAULT '[]',  -- [{step, delay_days, subject, body, cta}]
  babuu_generated BOOLEAN DEFAULT FALSE,
  performance JSONB,                     -- open rate, click rate, conversions per step
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sequences_brand ON message_sequences(brand_id);

-- ============================================================
-- SCHEDULING SUPPORT
-- content_calendar already has scheduled_for + status.
-- Add publish attempt tracking for the auto-scheduler cron.
-- ============================================================
ALTER TABLE content_calendar
  ADD COLUMN IF NOT EXISTS publish_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_publish_error TEXT,
  ADD COLUMN IF NOT EXISTS platform_post_id TEXT;  -- ID returned by the platform after publish

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_swipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_news_digests ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_sequences ENABLE ROW LEVEL SECURITY;

-- MVP policies: authenticated users see everything (single-team studio).
-- Tighten to per-user brand access before onboarding external clients.
CREATE POLICY tasks_all ON tasks FOR ALL USING (true);
CREATE POLICY swipes_all ON competitor_swipes FOR ALL USING (true);
CREATE POLICY knowledge_all ON knowledge_documents FOR ALL USING (true);
CREATE POLICY news_all ON ai_news_digests FOR ALL USING (true);
CREATE POLICY sequences_all ON message_sequences FOR ALL USING (true);

-- updated_at triggers (reuses set_updated_at() from schema.sql if present)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tasks_updated BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_swipes_updated BEFORE UPDATE ON competitor_swipes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_knowledge_updated BEFORE UPDATE ON knowledge_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sequences_updated BEFORE UPDATE ON message_sequences FOR EACH ROW EXECUTE FUNCTION set_updated_at();
